<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Chat.aspx.cs" Inherits="SignalRChat.Chat" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>SignalR Chat : Chat Page</title>
    <!------ Include the above in your HEAD tag ---------->

    <link href="Content/bootstrap.min.css" rel="stylesheet" />
    <link href="Scripts/bootstrap.min.js" rel="stylesheet" />
    <link href="Content/style.css" rel="stylesheet" />
    <link href="Content/font-awesome.css" rel="stylesheet" />
    <link href="css/style.css" rel="stylesheet" />

    <script src="Scripts/jQuery-3.2.1.min.js"></script>
    <script src="Scripts/jquery.signalR-2.2.2.min.js"></script>
    <script src="Scripts/date.format.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>


    <script type="text/javascript">


        var IntervalVal;
        $(function () {

            // Declare a proxy to reference the hub.
           
            var chatHub = $.connection.chatHub;
            registerClientMethods(chatHub);
            // Start Hub
            $.connection.hub.start().done(function () {

                registerEvents(chatHub)

            });

            // Reset Message Counter on Hover
            $("#divChatWindow").mouseover(function () {

                $("#MsgCountMain").html('0');
                $("#MsgCountMain").attr("title", '0 New Messages');
            });

            // Diplay Image Preview on File Upload 
            $(document).on('change', '#<%= FileUpload1.ClientID%>', function (e) {

                var tmppath = URL.createObjectURL(e.target.files[0]);
                $("#ImgDisp").attr('src', tmppath);

            });

            // Stop Title Alert
            window.onfocus = function (event) {
                if (event.explicitOriginalTarget === window) {

                    clearInterval(IntervalVal);
                    document.title = 'SignalR Chat App';
                }
            }

        });

        // Show Title Alert
        function ShowTitleAlert(newMessageTitle, pageTitle) {
            if (document.title == pageTitle) {
                document.title = newMessageTitle;
            }
            else {
                document.title = pageTitle;
            }
        }

        function registerEvents(chatHub) {

            var name = '<%= this.UserName %>';
          
            if (name.length > 0) {
                chatHub.server.connect(name);

            }

            $('#newGroupButton').click(function () {
                var groupName = $('#newGroupName').val();
                var userName = $('#hdUserName').val();
                chatHub.server.createGroup(groupName, userName);
                $('#newGroupName').val('');
            });

            // Send Button Click Event
            $('#btnSendMsg').click(function () {

                var msg = $("#txtMessage").val().trim();

                if (msg.length > 0) {

                    var userName = $('#hdUserName').val();

                    var date = GetCurrentDateTime(new Date());

                    chatHub.server.sendMessage(userName, msg, date, $('#actualChatId').val());
                    $("#txtMessage").val('');
                }
            });

            $('#divChatWindow').on("click", "#btnLoadMore", function () {
                $("#btnLoadMore").remove();

                var count = $("#messageCounter").val().trim();

                chatHub.server.getMessagesFromDb($('#actualChatId').val(), count);
            });

            // Send Message on Enter Button
            $("#txtMessage").keypress(function (e) {
                if (e.which == 13) {
                    $('#btnSendMsg').click();
                }
            });

             // Changing text of dropdown
            $(function () {
                $("#allUsers").click(function () {
                
                    $("#dropdownMenu2Text").text($(this).text());
                    $("#dropdownMenu2Text").val($(this).text());
                    chatHub.server.loadAllUsers(name);
               });

            });

            $(function () {
                $("#onlineUsers").click(function () {
                
                    $("#dropdownMenu2Text").text($(this).text());
                    $("#dropdownMenu2Text").val($(this).text());
                    chatHub.server.loadOnlineUsers(name);
                
               });

            });

            $(function () {
                $("#myGroups").click(function () {
                
                    $("#dropdownMenu2Text").text($(this).text());
                    $("#dropdownMenu2Text").val($(this).text());
                    chatHub.server.loadAllGroups(name);
               });

            });
        }

        function registerClientMethods(chatHub) {


            // Calls when user successfully logged in
            chatHub.client.onConnected = function (id, userName) {

                $('#hdId').val(id);
                $('#hdUserName').val(userName);
                $('#messageCounter').val("0");
                $('#actualChatId').val("1");
                
                // Load online users
                chatHub.server.loadOnlineUsers(userName);

                // Load messages
                chatHub.server.getMessagesFromDb($('#actualChatId').val(), $('#messageCounter').val());

            }

            // On New User Connected
            chatHub.client.onNewUserConnected = function (userName, UserImage) {
                var disc = $('<div class="disconnect">"' + userName + '" connected.</div>');

                $(disc).hide();
                $('#notificationConnected').prepend(disc);
                $(disc).fadeIn(200).delay(2000).fadeOut(200);
                
                    if (document.getElementById("dropdownMenu2Text").textContent != " Online users ") {
                        return;
                    }

                chatHub.client.loadAllUsers([ userName ], [ UserImage ] );
            }

            // On User Disconnected
            chatHub.client.onUserDisconnected = function (userName) {

                var disc = $('<div class="disconnect">"' + userName + '" disconnected.</div>');

                $(disc).hide();
                $('#notificationDisconnected').prepend(disc);
                $(disc).fadeIn(200).delay(2000).fadeOut(200);

                if (document.getElementById("dropdownMenu2Text").textContent != " Online users ") {
                        return;
                    }

                $('#li' + userName).remove();
            }

            chatHub.client.messageReceived = function (userName, message, time, userimg, groupId) {
                if (groupId == $('#actualChatId').val())
                    AddMessage(userName, message, time, userimg);

                // Display Message Count and Notification
                var CurrUser1 = $('#hdUserName').val();
                if (CurrUser1 != userName) {

                    var msgcount = $('#MsgCountMain').html();
                    msgcount++;
                    $("#MsgCountMain").html(msgcount);
                    $("#MsgCountMain").attr("title", msgcount + ' New Messages');
                    var Notification = 'New Message From ' + userName;
                    IntervalVal = setInterval("ShowTitleAlert('SignalR Chat App', '" + Notification + "')", 800);

                }
            }

            chatHub.client.selectNewChat = function (groupId, groupName) {
                changeChat(groupId, groupName, chatHub);
            }
        
            chatHub.client.loadAllGroups = function (groups, ids) {
                if ($('#dropdownMenu2Text').val() != " My groups ")
                    return;
                var div = document.getElementById("divusers");
                while (div.firstChild) {
                    div.removeChild(div.firstChild);
                }
                var i;
                for (i = 0; i < groups.length; i++) {
                    // Anonymous function to store groupId in click function
                    (function () {
                        var groupId = ids[i];
                        var groupName = groups[i];
                        code = $('<li class="left clearfix" id="group' + groupId+ '">' +
                            '<div class="chat-body clearfix"> <div class="header_sec"> <strong class="primary-font">' + groupName + '</strong>' +
                            '</div> </div></li>');

                        $(code).click(function () {
                            changeChat(groupId, groupName, chatHub);
                        });

                        $("#divusers").append(code);
                    })();
                }
            }


            chatHub.client.loadAllUsers = function (users, photos) {
                var div = document.getElementById("divusers");
                while (div.firstChild) {
                    div.removeChild(div.firstChild);
                }
                var i;
                for (i = 0; i < users.length; i++) {
                     // Anonymous function to store groupId in click function
                    (function () {
                        var username = users[i]
                        code = $('<li class="left clearfix" id="li' + username + '">' +
                            '<span class="chat-img pull-left">' +
                            '<img src="' + photos[i] + '" alt="User Avatar" class="img-circle img-sm">' +
                            '</span>' +
                            '<div class="chat-body clearfix"> <div class="header_sec"> <strong class="primary-font">' + username + '</strong>' +
                            '</div> </div></li>');

                        $(code).click(function () {
                            chatHub.server.openPrivateChat($('#hdUserName').val(), username);
                        });

                        $("#divusers").append(code);
                    })();
                }
            }

            chatHub.client.loadMessages = function (username, text, time, image) {
                var i;
                for (i = 0; i < username.length; i++) {
                    AddMessageCode(username[i], text[i], time[i], image[i], false);
                }
                
                var button = "<div class='bg-olive  text-center' id='btnLoadMore' >Load more</div>"
                $('#divChatWindow').prepend(button);
                
                // Scroll to the bottom of chat
                var scr = $("#chatScroll");
                scr.scrollTop(scr.prop("scrollHeight"));
            }

        }



        function GetCurrentDateTime(now) {

            var localdate = dateFormat(now, "d. m. yyyy H:MM:ss");

            return localdate;
        }

        function changeChat(chatId, chatName, chatHub) {
            
            $("#actualChatId").val(chatId);
            $('#messageCounter').val("0");
            $('#divChatWindow').empty();
            $('#chatName').text(chatName);
            chatHub.server.getMessagesFromDb($('#actualChatId').val(), $('#messageCounter').val());
        }
        

        function AddMessageCode(userName, message, time, userimg, bottom) {
            
            var CurrUser = $('#hdUserName').val();
            var Side = 'right';
            var TimeSide = 'left';

            if (CurrUser !== userName) {
                Side = 'left';
                TimeSide = 'right';

            }

            var divChat = '<div class="direct-chat-msg ' + Side + '">' +
                '<div class="direct-chat-info clearfix">' +
                '<span class="direct-chat-name pull-' + Side + '">' + userName + '</span>' +
                '<span class="direct-chat-timestamp pull-' + TimeSide + '"">' + time + '</span>' +
                '</div>' +

                ' <img class="direct-chat-img" src="' + userimg + '" alt="Message User Image">' +
                ' <div class="direct-chat-text" >' + message + '</div> </div>';

            incrementMessageCount();

            if (bottom) {
                $('#divChatWindow').append(divChat);
                var scr = $("#chatScroll");
                scr.scrollTop(scr.prop("scrollHeight"));
            }
            else {
                $('#divChatWindow').prepend(divChat);
                //var scr = $("#chatScroll");
                //scr.scrollTop(scr.prop("scrollHeight"));
            }
        }

        function AddMessage(userName, message, time, userimg) {

            AddMessageCode(userName,message,time,userimg, true)
            
        }

        function incrementMessageCount() {
            $('#messageCounter').val(function (i, oldval) {
                return ++oldval;
            });
        }


    </script>

</head>

<body>
    <form id="newGroupForm"></form>
<form id="form1" runat="server">
    <asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>
    <span id="time"></span>
    <input id="hdId" type="hidden"/>
    <input id="PWCount" type="hidden" value="info"/>
    <input id="hdUserName" type="hidden"/>
    <input id="messageCounter" type="hidden" value="0"/>
    <input id="actualChatId" type="hidden" value="1" />
    <div class="modal fade" id="ChangePic" role="dialog">
        <div class="modal-dialog" style="width: 700px">
            <div class="modal-content">
                <div class="modal-header bg-light-blue-gradient with-border">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Change Profile Picture</h4>
                </div>
                <div class="modal-body">
                    <div>
                        <asp:UpdatePanel ID="UpdatePanel1" runat="server">
                            <Triggers>
                                <asp:PostBackTrigger ControlID="btnChangePicModel"/>
                            </Triggers>
                            <ContentTemplate>
                                <div class="row">
                                    <div class="col-md-12">
                                        <table class="table table-bordered table-striped table-hover table-responsive" style="width: 600px">
                                            <tr>
                                                <div class="col-md-12">
                                                    <td class="text-primary col-md-4" style="font-weight: bold;">
                                                        <asp:FileUpload ID="FileUpload1" runat="server" class="btn btn-default"/>
                                                    </td>
                                                    <td class="col-md-4">
                                                        <asp:Button ID="btnChangePicModel" runat="server" Text="Update Picture" CssClass="btn btn-flat btn-success" OnClick="btnChangePicModel_Click"/>
                                                    </td>
                                                </div>
                                            </tr>
                                            <tr>
                                                <div class="col-md-12">
                                                    <td class="col-md-12" colspan="4"></td>
                                                </div>
                                            </tr>
                                        </table>
                                    </div>
                                </div>

                            </div>
                            </div>
                            </ContentTemplate>
                        </asp:UpdatePanel>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="Scripts/bootstrap.min.js"></script>
<div class="main_section">
<div class="container">
    <div id="notificationDisconnected" class="bg-danger text-center"></div>
    <div id="notificationConnected" class="bg-success text-center"></div>
<div class="chat_container">
<div class="col-sm-3 chat_sidebar">
    <div class="row">
        <div class="dropdown all_conversation">
            <button class="dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-weixin" aria-hidden="true"></i>
                <span id="dropdownMenu2Text"> Online users </span>
                <span class="caret pull-right"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
                <li>
                    <a href="#" id="onlineUsers"> Online users </a>
                </li>
                <li>
                    <a href="#" id="allUsers"> All users </a>
                </li>
                <li>
                    <a href="#" id="myGroups"> My groups </a>
                </li>
            </ul>
        </div>
        <ul class="list-unstyled">
        <div id="divusers" class="member_list">
        </div>
        </ul>
    </div>
</div>
<!--chat_sidebar-->
<div class="col-sm-9 message_section">
    <div class="row">
        <div class="new_message_head">

            <!-- Add new group -->
            <div class="pull-left">
                    <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- Messages: style can be found in dropdown.less-->

                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-plus-square-o" aria-hidden="true"></i> New group
                            </a>
                            <ul class="dropdown-menu">
                                <li class="user-footer">
                                        <input type="text" id="newGroupName" placeholder="Name" required="required" runat="server" form="newGroupForm"/>
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a class="btn btn-danger btn-flat" data-toggle="dropdown" href="#">Cancel</a>
                                    </div>
                                    <div class="pull-right">
                                        <a class="btn btn-success btn-flat" id="newGroupButton" data-toggle="dropdown" href="#">Create</a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                        <!-- Control Sidebar Toggle Button -->
                    </ul>
                </div>
            </div>
            
            <!-- User menu -->
            <div class="pull-right">
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- Messages: style can be found in dropdown.less-->

                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="<%= UserImage %>" class="user-image" alt="User Image"/>
                                <span class="hidden-xs"><%= this.UserName %></span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header">
                                    <img src="<%= UserImage %>" class="img-circle" alt="User Image"/>
                                    <p style="color: #000000;">
                                        <%= UserName %>
                                    </p>
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a class="btn btn-default btn-flat" data-toggle="modal" href="#ChangePic">Change Picture</a>
                                    </div>
                                    <div class="pull-right">
                                            <asp:Button ID="btnSignOut" runat="server" CssClass="btn btn-default btn-flat" Text="Sign Out" OnClick="btnSignOut_Click"/>
                                    </div>
                                </li>
                            </ul>
                        </li>
                        <!-- Control Sidebar Toggle Button -->
                    </ul>
                </div>
            </div>
            
            <div >
                <h2 id="chatName" class="text-center center-block">Global</h2>
            </div>
        </div><!--new_message_head-->
        <div class="chat_area" id="chatScroll">
                <!-- Conversations are loaded here -->
                <div id="chat-box">
                    <!-- Conversations are loaded here -->
                    <div id="divChatWindow">
                    </div>
                    
                    <!-- /.direct-chat-pane -->
                </div>
        </div><!--chat_area-->

        <div class="message_write">
            <textarea id="txtMessage" class="form-control" placeholder="type a message"></textarea>
            <div class="clearfix"></div>
            <div class="chat_bottom">
                <a href="#" class="pull-right btn btn-success " id="btnSendMsg" >
                    Send</a>
            </div>
        </div>
    </div>
</div> <!--message_section-->
</div>
</div>
</div>
</form>
</body>
</html>
